server:
  port: 8090
logging.level:
  org.springframework: error
restPath: /a/rest

#============================#
#===== Database settings =====#
#============================#
spring.datasource:
  url: jdbc:mysql://127.0.0.1:3306/bidding?useUnicode=true&characterEncoding=utf-8
  username: root
  password: one
  driver-class-name: com.mysql.jdbc.Driver
  druid.initialSize: 3
  druid.maxActive: 3
  druid.minIdle: 2
  druid.maxWait: 60000
  druid.timeBetweenEvictionRunsMillis: 60000
  druid.minEvictableIdleTimeMillis: 300000
  druid.validationQuery: SELECT 'x' FROM DUAL
hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  show_sql: true